'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';

export default function Register(){
 const [form,setForm]=useState({name:'',email:'',phone:'',abha:'',password:''}); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [busy,setBusy]=useState(false); const [resending,setResending]=useState(false); const router=useRouter(); const update=(key:string,value:string)=>setForm(old=>({...old,[key]:value}));
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');setSuccess('');try{if(!form.name.trim()||!form.email.includes('@')||form.password.length<6)throw new Error('Enter your name, a valid email and a password of at least 6 characters.');const phone=form.phone.replace(/\D/g,'');const {data,error:signupError}=await supabase.auth.signUp({email:form.email.trim(),password:form.password,options:{data:{full_name:form.name.trim(),phone:phone?`+91${phone}`:null,abha_id:form.abha.trim()||null}}});if(signupError)throw signupError;if(!data.session){setSuccess('Account created. Confirm the email sent by Supabase, then return here and sign in. If it is not in Inbox, check Spam/Junk or use Resend confirmation below.');return}const ensured=await supabase.rpc('ensure_current_patient');if(ensured.error)throw new Error('Account created, but the patient profile could not be opened. Run the latest Supabase migration, then sign in again.');const updated=await supabase.from('patients').update({full_name:form.name.trim(),email:form.email.trim(),phone:phone?`+91${phone}`:null,abha_id:form.abha.trim()||null}).eq('user_id',data.user?.id||'');if(updated.error)throw updated.error;router.push('/patient/dashboard')}catch(caught){setError(caught instanceof Error?caught.message:'Could not create your account.')}finally{setBusy(false)}}
 async function resend(){if(!form.email.includes('@')){setError('Enter the same valid email address first.');return}setResending(true);setError('');const {error}=await supabase.auth.resend({type:'signup',email:form.email.trim()});if(error)setError(error.message);else setSuccess('Confirmation email requested again. Check Inbox and Spam/Junk.');setResending(false)}
 return <main className="min-h-screen bg-[#edf6f6] p-4 py-8"><form onSubmit={submit} className="mx-auto max-w-md rounded-[28px] bg-white p-6 shadow-soft"><Link href="/patient/login" className="text-sm font-bold text-calm">← Back to sign in</Link><p className="clinical-eyebrow mt-6">Patient self-registration</p><h1 className="mt-1 text-2xl font-extrabold">Create your AarogyaVaani account</h1><p className="mt-2 text-sm leading-5 text-slate-600">Register yourself to access appointments, records and check-in services.</p><label className="label mt-6">Full name</label><input className="input" value={form.name} onChange={e=>update('name',e.target.value)} required/><label className="label mt-4">Email address</label><input className="input" type="email" value={form.email} onChange={e=>update('email',e.target.value)} required/><label className="label mt-4">Mobile number <span className="font-normal text-slate-400">optional</span></label><input className="input" inputMode="numeric" maxLength={10} value={form.phone} onChange={e=>update('phone',e.target.value.replace(/\D/g,''))} placeholder="98765 43210"/><label className="label mt-4">ABHA ID <span className="font-normal text-slate-400">optional</span></label><input className="input" value={form.abha} onChange={e=>update('abha',e.target.value)} placeholder="12-3456-7890-1234"/><label className="label mt-4">Create password</label><input className="input" type="password" minLength={6} value={form.password} onChange={e=>update('password',e.target.value)} required/><button className="btn-primary mt-6 w-full rounded-2xl py-3.5" disabled={busy}>{busy?'Creating account…':'Create patient account'}</button>{success&&<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><p>{success}</p><button type="button" onClick={resend} disabled={resending} className="mt-2 font-bold underline">{resending?'Requesting…':'Resend confirmation email'}</button><span> · </span><Link className="font-bold underline" href="/patient/login">Go to sign in</Link></div>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="mt-4 text-xs leading-5 text-slate-500">Email delivery is sent by Supabase. If resend also does not arrive, configure SMTP in Supabase Authentication → Emails.</p></form></main>;
}
