'use client';

import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Details = { blood_group:string|null; allergies:string|null; chronic_conditions:string|null; critical_medications:string|null; emergency_contact:string|null };
const fields: Array<[keyof Details,string,string]> = [['blood_group','Blood group','e.g. O positive'],['allergies','Allergies','List known allergies'],['chronic_conditions','Chronic conditions','List ongoing conditions'],['critical_medications','Critical medicines','Medicines needed in an emergency'],['emergency_contact','Emergency contact','Name and phone number']];
export function EmergencyInformation(){
 const [patientId,setPatientId]=useState(''); const [details,setDetails]=useState<Details>({blood_group:'',allergies:'',chronic_conditions:'',critical_medications:'',emergency_contact:''}); const [notice,setNotice]=useState(''); const [limited,setLimited]=useState<Details|null>(null);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error}=await supabase.from('patients').select('id,blood_group,allergies,chronic_conditions,critical_medications,emergency_contact').eq('user_id',user.id).single();if(error){setNotice('Emergency information will be available after the clinical migration is applied.');return}setPatientId(data.id);setDetails(data)})()},[]);
 async function save(event:FormEvent){event.preventDefault();if(!patientId)return;const {error}=await supabase.from('patients').update(details).eq('id',patientId);setNotice(error?.message||'Emergency information saved privately.');}
 async function access(){if(!patientId)return;const {data,error}=await supabase.rpc('emergency_patient_info',{p_patient_id:patientId,p_reason:'Patient reviewed own emergency information'});if(error){setNotice(error.message);return}setLimited((data||[])[0]||null);setNotice('Emergency-only details opened. This view was logged.');}
 return <section className="clinical-card mt-5 p-5"><p className="clinical-eyebrow">Emergency information</p><h2 className="mt-1 text-xl font-extrabold">Essential details only</h2><p className="mt-2 text-sm leading-5 text-slate-600">Keep these details current for an emergency. This does not grant unrestricted access to your health record.</p><form onSubmit={save} className="mt-4 grid gap-3">{fields.map(([key,label,placeholder])=><label key={key} className="text-sm font-bold text-slate-700">{label}<input className="input mt-1" value={details[key]||''} placeholder={placeholder} onChange={e=>setDetails(old=>({...old,[key]:e.target.value}))}/></label>)}<button className="btn-secondary mt-1" type="submit">Save emergency information</button></form><button type="button" onClick={access} className="btn-primary mt-3 w-full">Emergency Access</button>{notice&&<p className="mt-3 rounded-xl bg-cyan-50 p-3 text-sm text-cyan-900">{notice}</p>}{limited&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-slate-700"><b>Emergency-only view</b><p className="mt-1">Blood group: {limited.blood_group||'Not recorded'}</p><p>Allergies: {limited.allergies||'Not recorded'}</p><p>Critical medicines: {limited.critical_medications||'Not recorded'}</p><p>Emergency contact: {limited.emergency_contact||'Not recorded'}</p></div>}</section>;
}
