'use client';

import { useEffect, useState } from 'react';
import { languages, LANGUAGE_STORAGE_KEY } from '@/lib/languages';

type Locale = typeof languages[number]['code'];
type Dictionary = Record<string, string>;

/* The app uses one shared language layer so a selection is honoured on every route. */
const dictionaries: Partial<Record<Locale, Dictionary>> = {
  'hi-IN': {
    'Choose language':'भाषा चुनें','Patient Portal':'मरीज पोर्टल','Doctor Portal':'डॉक्टर पोर्टल','Hospital Kiosk':'अस्पताल कियोस्क','Choose portal access →':'पोर्टल चुनें →','Open portal →':'पोर्टल खोलें →','Continue →':'आगे बढ़ें →','Patient portal':'मरीज पोर्टल','Doctor portal':'डॉक्टर पोर्टल','Hospital kiosk':'अस्पताल कियोस्क','Continue with Google':'Google से जारी रखें','Email address':'ईमेल पता','Send secure sign-in link':'सुरक्षित साइन-इन लिंक भेजें','Sign in to AarogyaVaani':'आरोग्यवाणी में साइन इन करें','Care connected for every patient.':'हर मरीज के लिए जुड़ी हुई देखभाल।','YOUR HEALTH · YOUR RECORDS':'आपका स्वास्थ्य · आपके रिकॉर्ड','Digital Health System':'डिजिटल स्वास्थ्य प्रणाली','Existing patient':'मौजूदा मरीज','New patient registration':'नया मरीज पंजीकरण','Check appointment':'अपॉइंटमेंट जाँचें','Scan QR':'QR स्कैन करें','Welcome to your visit':'आपकी यात्रा में आपका स्वागत है','Hospital self-service kiosk':'अस्पताल स्वयं-सेवा कियोस्क','Check in now':'अभी चेक इन करें','Appointment check-in code':'अपॉइंटमेंट चेक-इन कोड','Open camera scanner':'कैमरा स्कैनर खोलें','Back to kiosk home':'कियोस्क होम पर वापस जाएँ','Doctor sign in':'डॉक्टर साइन इन','Doctor ID or email':'डॉक्टर आईडी या ईमेल','Password':'पासवर्ड','Secure doctor sign in →':'सुरक्षित डॉक्टर साइन इन →','My health locker':'मेरा स्वास्थ्य लॉकर','Appointments':'अपॉइंटमेंट','My medicines':'मेरी दवाएँ','Health interview':'स्वास्थ्य साक्षात्कार','Medication history':'दवा इतिहास','Which medicines are you using now?':'आप अभी कौन सी दवाएँ ले रहे हैं?','Book appointment':'अपॉइंटमेंट बुक करें','Request appointment':'अपॉइंटमेंट अनुरोध करें','Doctor':'डॉक्टर','Date':'तारीख','Time':'समय','Reason for visit':'मिलने का कारण','Request an appointment':'अपॉइंटमेंट का अनुरोध करें','Sign out':'साइन आउट','Home':'होम','Records':'रिकॉर्ड','Profile':'प्रोफ़ाइल','Interview':'साक्षात्कार'
  },
  'mr-IN': {
    'Choose language':'भाषा निवडा','Patient Portal':'रुग्ण पोर्टल','Doctor Portal':'डॉक्टर पोर्टल','Hospital Kiosk':'रुग्णालय किऑस्क','Choose portal access →':'पोर्टल निवडा →','Open portal →':'पोर्टल उघडा →','Continue →':'पुढे जा →','Patient portal':'रुग्ण पोर्टल','Doctor portal':'डॉक्टर पोर्टल','Hospital kiosk':'रुग्णालय किऑस्क','Continue with Google':'Google सह सुरू ठेवा','Email address':'ईमेल पत्ता','Send secure sign-in link':'सुरक्षित साइन-इन लिंक पाठवा','Sign in to AarogyaVaani':'आरोग्यवाणीमध्ये साइन इन करा','Care connected for every patient.':'प्रत्येक रुग्णासाठी जोडलेली काळजी.','Existing patient':'विद्यमान रुग्ण','New patient registration':'नवीन रुग्ण नोंदणी','Check appointment':'अपॉइंटमेंट तपासा','Scan QR':'QR स्कॅन करा','Welcome to your visit':'तुमच्या भेटीचे स्वागत आहे','Doctor sign in':'डॉक्टर साइन इन','Doctor ID or email':'डॉक्टर आयडी किंवा ईमेल','Password':'पासवर्ड','My health locker':'माझे आरोग्य लॉकर','Appointments':'अपॉइंटमेंट','My medicines':'माझी औषधे','Medication history':'औषधांचा इतिहास','Book appointment':'अपॉइंटमेंट बुक करा','Date':'तारीख','Time':'वेळ','Doctor':'डॉक्टर','Home':'मुख्यपृष्ठ','Records':'नोंदी','Profile':'प्रोफाइल'
  },
  'ur-IN': {
    'Choose language':'زبان منتخب کریں','Patient Portal':'مریض پورٹل','Doctor Portal':'ڈاکٹر پورٹل','Hospital Kiosk':'ہسپتال کیوسک','Choose portal access →':'پورٹل منتخب کریں →','Open portal →':'پورٹل کھولیں →','Continue →':'جاری رکھیں →','Patient portal':'مریض پورٹل','Doctor portal':'ڈاکٹر پورٹل','Hospital kiosk':'ہسپتال کیوسک','Continue with Google':'Google کے ساتھ جاری رکھیں','Email address':'ای میل پتہ','Send secure sign-in link':'محفوظ سائن اِن لنک بھیجیں','Sign in to AarogyaVaani':'آروگیہ وانی میں سائن اِن کریں','Care connected for every patient.':'ہر مریض کے لیے مربوط نگہداشت۔','Existing patient':'موجودہ مریض','New patient registration':'نئے مریض کی رجسٹریشن','Check appointment':'اپوائنٹمنٹ چیک کریں','Scan QR':'QR اسکین کریں','Welcome to your visit':'آپ کی ملاقات میں خوش آمدید','Doctor sign in':'ڈاکٹر سائن اِن','Doctor ID or email':'ڈاکٹر آئی ڈی یا ای میل','Password':'پاس ورڈ','My health locker':'میرا ہیلتھ لاکر','Appointments':'اپوائنٹمنٹس','My medicines':'میری دوائیں','Medication history':'ادویات کی تاریخ','Book appointment':'اپوائنٹمنٹ بک کریں','Date':'تاریخ','Time':'وقت','Doctor':'ڈاکٹر','Home':'ہوم','Records':'ریکارڈز','Profile':'پروفائل'
  },
  'pa-IN': {
    'Choose language':'ਭਾਸ਼ਾ ਚੁਣੋ','Patient Portal':'ਮਰੀਜ਼ ਪੋਰਟਲ','Doctor Portal':'ਡਾਕਟਰ ਪੋਰਟਲ','Hospital Kiosk':'ਹਸਪਤਾਲ ਕਿਓਸਕ','Choose portal access →':'ਪੋਰਟਲ ਚੁਣੋ →','Open portal →':'ਪੋਰਟਲ ਖੋਲ੍ਹੋ →','Continue →':'ਜਾਰੀ ਰੱਖੋ →','Patient portal':'ਮਰੀਜ਼ ਪੋਰਟਲ','Doctor portal':'ਡਾਕਟਰ ਪੋਰਟਲ','Hospital kiosk':'ਹਸਪਤਾਲ ਕਿਓਸਕ','Continue with Google':'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ','Email address':'ਈਮੇਲ ਪਤਾ','Send secure sign-in link':'ਸੁਰੱਖਿਅਤ ਸਾਈਨ-ਇਨ ਲਿੰਕ ਭੇਜੋ','Sign in to AarogyaVaani':'ਆਰੋਗਿਆਵਾਣੀ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ','Care connected for every patient.':'ਹਰ ਮਰੀਜ਼ ਲਈ ਜੁੜੀ ਦੇਖਭਾਲ।','Existing patient':'ਮੌਜੂਦਾ ਮਰੀਜ਼','New patient registration':'ਨਵਾਂ ਮਰੀਜ਼ ਰਜਿਸਟ੍ਰੇਸ਼ਨ','Check appointment':'ਮੁਲਾਕਾਤ ਜਾਂਚੋ','Scan QR':'QR ਸਕੈਨ ਕਰੋ','Welcome to your visit':'ਤੁਹਾਡੀ ਮੁਲਾਕਾਤ ਵਿੱਚ ਸੁਆਗਤ ਹੈ','Doctor sign in':'ਡਾਕਟਰ ਸਾਈਨ ਇਨ','Doctor ID or email':'ਡਾਕਟਰ ਆਈਡੀ ਜਾਂ ਈਮੇਲ','Password':'ਪਾਸਵਰਡ','My health locker':'ਮੇਰਾ ਸਿਹਤ ਲਾਕਰ','Appointments':'ਮੁਲਾਕਾਤਾਂ','My medicines':'ਮੇਰੀਆਂ ਦਵਾਈਆਂ','Medication history':'ਦਵਾਈ ਇਤਿਹਾਸ','Book appointment':'ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ','Date':'ਤਾਰੀਖ','Time':'ਸਮਾਂ','Doctor':'ਡਾਕਟਰ','Home':'ਹੋਮ','Records':'ਰਿਕਾਰਡ','Profile':'ਪ੍ਰੋਫਾਈਲ'
  },
  'kn-IN': {
    'Choose language':'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ','Patient Portal':'ರೋಗಿ ಪೋರ್ಟಲ್','Doctor Portal':'ವೈದ್ಯರ ಪೋರ್ಟಲ್','Hospital Kiosk':'ಆಸ್ಪತ್ರೆ ಕಿಯೋಸ್ಕ್','Choose portal access →':'ಪೋರ್ಟಲ್ ಆಯ್ಕೆಮಾಡಿ →','Open portal →':'ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ →','Continue →':'ಮುಂದುವರಿಸಿ →','Patient portal':'ರೋಗಿ ಪೋರ್ಟಲ್','Doctor portal':'ವೈದ್ಯರ ಪೋರ್ಟಲ್','Hospital kiosk':'ಆಸ್ಪತ್ರೆ ಕಿಯೋಸ್ಕ್','Continue with Google':'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ','Email address':'ಇಮೇಲ್ ವಿಳಾಸ','Send secure sign-in link':'ಸುರಕ್ಷಿತ ಸೈನ್-ಇನ್ ಲಿಂಕ್ ಕಳುಹಿಸಿ','Sign in to AarogyaVaani':'ಆರೋಗ್ಯವಾಣಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ','Care connected for every patient.':'ಪ್ರತಿ ರೋಗಿಗೂ ಸಂಪರ್ಕಿತ ಆರೈಕೆ.','Existing patient':'ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ರೋಗಿ','New patient registration':'ಹೊಸ ರೋಗಿ ನೋಂದಣಿ','Check appointment':'ನೇಮಕಾತಿ ಪರಿಶೀಲಿಸಿ','Scan QR':'QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ','Welcome to your visit':'ನಿಮ್ಮ ಭೇಟಿಗೆ ಸ್ವಾಗತ','Doctor sign in':'ವೈದ್ಯರ ಸೈನ್ ಇನ್','Doctor ID or email':'ವೈದ್ಯರ ಐಡಿ ಅಥವಾ ಇಮೇಲ್','Password':'ಪಾಸ್‌ವರ್ಡ್','My health locker':'ನನ್ನ ಆರೋಗ್ಯ ಲಾಕರ್','Appointments':'ನೇಮಕಾತಿಗಳು','My medicines':'ನನ್ನ ಔಷಧಿಗಳು','Medication history':'ಔಷಧಿ ಇತಿಹಾಸ','Book appointment':'ನೇಮಕಾತಿ ಬುಕ್ ಮಾಡಿ','Date':'ದಿನಾಂಕ','Time':'ಸಮಯ','Doctor':'ವೈದ್ಯರು','Home':'ಮುಖಪುಟ','Records':'ದಾಖಲೆಗಳು','Profile':'ಪ್ರೊಫೈಲ್'
  },
  'ta-IN': {
    'Choose language':'மொழியைத் தேர்ந்தெடுக்கவும்','Patient Portal':'நோயாளர் தளம்','Doctor Portal':'மருத்துவர் தளம்','Hospital Kiosk':'மருத்துவமனை கியோஸ்க்','Choose portal access →':'தளத்தைத் தேர்ந்தெடுக்கவும் →','Open portal →':'தளத்தைத் திறக்கவும் →','Continue →':'தொடரவும் →','Patient portal':'நோயாளர் தளம்','Doctor portal':'மருத்துவர் தளம்','Hospital kiosk':'மருத்துவமனை கியோஸ்க்','Continue with Google':'Google மூலம் தொடரவும்','Email address':'மின்னஞ்சல் முகவரி','Send secure sign-in link':'பாதுகாப்பான உள்நுழைவு இணைப்பை அனுப்பவும்','Sign in to AarogyaVaani':'ஆரோக்யவாணியில் உள்நுழையவும்','Care connected for every patient.':'ஒவ்வொரு நோயாளிக்கும் இணைந்த பராமரிப்பு.','Existing patient':'ஏற்கனவே உள்ள நோயாளர்','New patient registration':'புதிய நோயாளர் பதிவு','Check appointment':'சந்திப்பைச் சரிபார்க்கவும்','Scan QR':'QR ஸ்கேன் செய்யவும்','Welcome to your visit':'உங்கள் வருகைக்கு வரவேற்கிறோம்','Doctor sign in':'மருத்துவர் உள்நுழைவு','Doctor ID or email':'மருத்துவர் ஐடி அல்லது மின்னஞ்சல்','Password':'கடவுச்சொல்','My health locker':'என் சுகாதார பெட்டி','Appointments':'சந்திப்புகள்','My medicines':'என் மருந்துகள்','Medication history':'மருந்து வரலாறு','Book appointment':'சந்திப்பைப் பதிவு செய்யவும்','Date':'தேதி','Time':'நேரம்','Doctor':'மருத்துவர்','Home':'முகப்பு','Records':'பதிவுகள்','Profile':'சுயவிவரம்'
  },
  'te-IN': {
    'Choose language':'భాషను ఎంచుకోండి','Patient Portal':'రోగి పోర్టల్','Doctor Portal':'వైద్యుల పోర్టల్','Hospital Kiosk':'ఆసుపత్రి కియోస్క్','Choose portal access →':'పోర్టల్ ఎంచుకోండి →','Open portal →':'పోర్టల్ తెరవండి →','Continue →':'కొనసాగించండి →','Patient portal':'రోగి పోర్టల్','Doctor portal':'వైద్యుల పోర్టల్','Hospital kiosk':'ఆసుపత్రి కియోస్క్','Continue with Google':'Googleతో కొనసాగించండి','Email address':'ఇమెయిల్ చిరునామా','Send secure sign-in link':'సురక్షిత సైన్-ఇన్ లింక్ పంపండి','Sign in to AarogyaVaani':'ఆరోగ్యవాణిలో సైన్ ఇన్ చేయండి','Care connected for every patient.':'ప్రతి రోగికి అనుసంధానమైన సంరక్షణ.','Existing patient':'ఉన్న రోగి','New patient registration':'కొత్త రోగి నమోదు','Check appointment':'అపాయింట్‌మెంట్ తనిఖీ చేయండి','Scan QR':'QR స్కాన్ చేయండి','Welcome to your visit':'మీ సందర్శనకు స్వాగతం','Doctor sign in':'వైద్యుల సైన్ ఇన్','Doctor ID or email':'వైద్యుల ఐడి లేదా ఇమెయిల్','Password':'పాస్‌వర్డ్','My health locker':'నా ఆరోగ్య లాకర్','Appointments':'అపాయింట్‌మెంట్లు','My medicines':'నా మందులు','Medication history':'మందుల చరిత్ర','Book appointment':'అపాయింట్‌మెంట్ బుక్ చేయండి','Date':'తేదీ','Time':'సమయం','Doctor':'వైద్యుడు','Home':'హోమ్','Records':'రికార్డులు','Profile':'ప్రొఫైల్'
  }
};

const medicineHistory: Partial<Record<Locale, Dictionary>> = {
  'hi-IN': {'Care information':'देखभाल की जानकारी','Patient-reported information':'मरीज द्वारा दी गई जानकारी','Which medicines are you using now?':'आप अभी कौन सी दवाएँ ले रहे हैं?','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'अस्पताल सूची में दवा खोजने के लिए लिखना शुरू करें। यह आपकी बताई जानकारी दर्ज करता है—यह उपचार की सलाह नहीं है।','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'अपनी देखभाल टीम को बताएं कि आप अभी कौन सी दवाएं ले रहे हैं। दवा शुरू करने, बदलने या बंद करने के लिए हमेशा चिकित्सक की सलाह मानें।','Medicine name':'दवा का नाम','How are you using it?':'आप इसे कैसे ले रहे हैं?','optional':'वैकल्पिक','Add medicine':'दवा जोड़ें'},
  'mr-IN': {'Care information':'काळजीविषयक माहिती','Patient-reported information':'रुग्णाने दिलेली माहिती','Which medicines are you using now?':'तुम्ही सध्या कोणती औषधे घेत आहात?','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'रुग्णालयाच्या सूचीतील औषध शोधण्यासाठी टाइप करा. हे तुमची माहिती नोंदवते—हा उपचाराचा सल्ला नाही.','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'तुम्ही वापरत असलेल्या औषधांची माहिती तुमच्या काळजी टीमला द्या. औषध सुरू, बदल किंवा बंद करण्यासाठी डॉक्टरांचा सल्ला घ्या.','Medicine name':'औषधाचे नाव','How are you using it?':'तुम्ही ते कसे घेत आहात?','optional':'ऐच्छिक','Add medicine':'औषध जोडा'},
  'ur-IN': {'Care information':'نگہداشت کی معلومات','Patient-reported information':'مریض کی فراہم کردہ معلومات','Which medicines are you using now?':'آپ اس وقت کون سی دوائیں استعمال کر رہے ہیں؟','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'ہسپتال کی فہرست میں دوا تلاش کرنے کے لیے لکھنا شروع کریں۔ یہ آپ کی دی گئی معلومات محفوظ کرتا ہے—یہ علاج کی سفارش نہیں ہے۔','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'اپنی نگہداشت ٹیم کو بتائیں کہ آپ کون سی دوائیں استعمال کر رہے ہیں۔ دوا شروع، تبدیل یا بند کرنے کے لیے ڈاکٹر کے مشورے پر عمل کریں۔','Medicine name':'دوا کا نام','How are you using it?':'آپ اسے کیسے استعمال کر رہے ہیں؟','optional':'اختیاری','Add medicine':'دوا شامل کریں'},
  'pa-IN': {'Care information':'ਦੇਖਭਾਲ ਜਾਣਕਾਰੀ','Patient-reported information':'ਮਰੀਜ਼ ਵੱਲੋਂ ਦਿੱਤੀ ਜਾਣਕਾਰੀ','Which medicines are you using now?':'ਤੁਸੀਂ ਇਸ ਵੇਲੇ ਕਿਹੜੀਆਂ ਦਵਾਈਆਂ ਵਰਤ ਰਹੇ ਹੋ?','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'ਹਸਪਤਾਲ ਸੂਚੀ ਤੋਂ ਦਵਾਈ ਲੱਭਣ ਲਈ ਲਿਖਣਾ ਸ਼ੁਰੂ ਕਰੋ। ਇਹ ਤੁਹਾਡੀ ਦਿੱਤੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰਦਾ ਹੈ—ਇਹ ਇਲਾਜ ਦੀ ਸਿਫਾਰਸ਼ ਨਹੀਂ ਹੈ।','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'ਆਪਣੀ ਦੇਖਭਾਲ ਟੀਮ ਨੂੰ ਆਪਣੀਆਂ ਮੌਜੂਦਾ ਦਵਾਈਆਂ ਬਾਰੇ ਦੱਸੋ। ਦਵਾਈ ਸ਼ੁਰੂ, ਬਦਲਣ ਜਾਂ ਬੰਦ ਕਰਨ ਲਈ ਡਾਕਟਰ ਦੀ ਸਲਾਹ ਮੰਨੋ।','Medicine name':'ਦਵਾਈ ਦਾ ਨਾਮ','How are you using it?':'ਤੁਸੀਂ ਇਹ ਕਿਵੇਂ ਲੈ ਰਹੇ ਹੋ?','optional':'ਵਿਕਲਪਿਕ','Add medicine':'ਦਵਾਈ ਸ਼ਾਮਲ ਕਰੋ'},
  'kn-IN': {'Care information':'ಆರೈಕೆ ಮಾಹಿತಿ','Patient-reported information':'ರೋಗಿ ನೀಡಿದ ಮಾಹಿತಿ','Which medicines are you using now?':'ನೀವು ಈಗ ಯಾವ ಔಷಧಿಗಳನ್ನು ಬಳಸುತ್ತಿದ್ದೀರಿ?','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'ಆಸ್ಪತ್ರೆ ಪಟ್ಟಿಯಲ್ಲಿ ಔಷಧಿ ಹುಡುಕಲು ಟೈಪ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ. ಇದು ನೀವು ತಿಳಿಸಿದ ಮಾಹಿತಿಯನ್ನು ದಾಖಲಿಸುತ್ತದೆ—ಇದು ಚಿಕಿತ್ಸೆಯ ಸಲಹೆಯಲ್ಲ.','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'ನೀವು ಬಳಸುತ್ತಿರುವ ಔಷಧಿಗಳ ಬಗ್ಗೆ ಆರೈಕೆ ತಂಡಕ್ಕೆ ತಿಳಿಸಿ. ಔಷಧಿ ಆರಂಭಿಸಲು, ಬದಲಿಸಲು ಅಥವಾ ನಿಲ್ಲಿಸಲು ವೈದ್ಯರ ಸಲಹೆ ಅನುಸರಿಸಿ.','Medicine name':'ಔಷಧಿಯ ಹೆಸರು','How are you using it?':'ನೀವು ಇದನ್ನು ಹೇಗೆ ಬಳಸುತ್ತಿದ್ದೀರಿ?','optional':'ಐಚ್ಛಿಕ','Add medicine':'ಔಷಧಿ ಸೇರಿಸಿ'},
  'ta-IN': {'Care information':'பராமரிப்பு தகவல்','Patient-reported information':'நோயாளர் வழங்கிய தகவல்','Which medicines are you using now?':'நீங்கள் இப்போது எந்த மருந்துகளைப் பயன்படுத்துகிறீர்கள்?','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'மருத்துவமனை பட்டியலில் மருந்தைத் தேட தட்டச்சு செய்யத் தொடங்குங்கள். இது நீங்கள் தெரிவித்த தகவலைப் பதிவு செய்கிறது—இது சிகிச்சை பரிந்துரை அல்ல.','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'நீங்கள் பயன்படுத்தும் மருந்துகளைப் பற்றி பராமரிப்பு குழுவுக்கு தெரிவியுங்கள். மருந்தைத் தொடங்க, மாற்ற அல்லது நிறுத்த மருத்துவரின் ஆலோசனையைப் பின்பற்றவும்.','Medicine name':'மருந்தின் பெயர்','How are you using it?':'நீங்கள் இதை எவ்வாறு பயன்படுத்துகிறீர்கள்?','optional':'விருப்பத்தேர்வு','Add medicine':'மருந்தைச் சேர்க்கவும்'},
  'te-IN': {'Care information':'సంరక్షణ సమాచారం','Patient-reported information':'రోగి అందించిన సమాచారం','Which medicines are you using now?':'మీరు ఇప్పుడు ఏ మందులు వాడుతున్నారు?','Start typing to find a medicine from the hospital catalogue. This records what you report—it is not a treatment recommendation.':'ఆసుపత్రి జాబితాలో మందు కనుగొనడానికి టైప్ చేయడం ప్రారంభించండి. ఇది మీరు తెలిపిన సమాచారాన్ని నమోదు చేస్తుంది—ఇది చికిత్స సిఫార్సు కాదు.','Help your care team understand medicines you are currently using. Always follow your clinician’s advice for starting, changing, or stopping medicine.':'మీరు వాడుతున్న మందుల గురించి సంరక్షణ బృందానికి తెలియజేయండి. మందును ప్రారంభించడానికి, మార్చడానికి లేదా ఆపడానికి వైద్యుని సలహాను అనుసరించండి.','Medicine name':'మందు పేరు','How are you using it?':'మీరు దీన్ని ఎలా వాడుతున్నారు?','optional':'ఐచ్ఛికం','Add medicine':'మందు జోడించండి'}
};

const originalText = new WeakMap<Text, string>();
function translate(value: string, locale: Locale) { return locale === 'en-IN' ? value : (dictionaries[locale]?.[value] || medicineHistory[locale]?.[value] || value); }
function applyLanguage(locale: Locale) {
  document.documentElement.lang = locale;
  document.documentElement.dir = languages.find(language => language.code === locale)?.direction || 'ltr';
  const walk = (node: Node) => {
    if (node.nodeType === Node.TEXT_NODE) {
      const textNode = node as Text; const parent = textNode.parentElement;
      if (!parent || parent.closest('[data-language-picker]') || ['SCRIPT','STYLE','OPTION'].includes(parent.tagName)) return;
      const source = originalText.get(textNode) ?? textNode.nodeValue ?? ''; originalText.set(textNode, source);
      const leading = source.match(/^\s*/)?.[0] ?? ''; const trailing = source.match(/\s*$/)?.[0] ?? ''; const content = source.trim();
      const next = `${leading}${translate(content, locale)}${trailing}`;
      if (textNode.nodeValue !== next) textNode.nodeValue = next;
      return;
    }
    node.childNodes.forEach(walk);
  };
  walk(document.body);
  document.querySelectorAll<HTMLElement>('[placeholder],[aria-label]').forEach(element => {
    if (element.closest('[data-language-picker]')) return;
    for (const attribute of ['placeholder','aria-label']) {
      const sourceKey = `i18n${attribute.replace('-', '')}`; const source = element.dataset[sourceKey] || element.getAttribute(attribute);
      if (!source) continue; element.dataset[sourceKey] = source; const next = translate(source, locale); if (element.getAttribute(attribute) !== next) element.setAttribute(attribute, next);
    }
  });
}

export function LanguagePicker({ dark = false }: { dark?: boolean }) {
  const [value, setValue] = useState<Locale>('en-IN');
  useEffect(() => {
    const refresh = () => { const next = (localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en-IN') as Locale; setValue(next); requestAnimationFrame(() => applyLanguage(next)); };
    refresh(); window.addEventListener('aarogyavaani-language', refresh);
    const observer = new MutationObserver(() => requestAnimationFrame(() => applyLanguage((localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en-IN') as Locale)));
    observer.observe(document.body, { childList: true, subtree: true }); return () => { window.removeEventListener('aarogyavaani-language', refresh); observer.disconnect(); };
  }, []);
  return <label data-language-picker className={`flex items-center gap-1 rounded-full border px-2 py-1 text-xs font-bold ${dark ? 'border-white/20 bg-white/10 text-white' : 'border-slate-200 bg-white text-slate-700'}`}><span aria-hidden>🌐</span><select aria-label="Choose language" className="max-w-24 bg-transparent outline-none" value={value} onChange={event => { const next = event.target.value as Locale; setValue(next); localStorage.setItem(LANGUAGE_STORAGE_KEY, next); applyLanguage(next); window.dispatchEvent(new Event('aarogyavaani-language')); }}>{languages.map(language => <option className="text-slate-900" key={language.code} value={language.code}>{language.label}</option>)}</select></label>;
}
