'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Prescription = { id:string; medicine_name:string; dosage:string|null; duration:string|null; instructions:string|null; meal_timing:string|null; frequency_note:string|null; morning:boolean|null; afternoon:boolean|null; evening:boolean|null; night:boolean|null; created_at:string };
type Log = { prescription_id:string; time_of_day:string; status:'taken'|'skipped' };
const slots=[['Morning','8:00 AM','morning'],['Afternoon','2:00 PM','afternoon'],['Evening','8:00 PM','evening'],['Night','10:00 PM','night']] as const;

export function PatientTreatmentRoutine(){
 const [prescriptions,setPrescriptions]=useState<Prescription[]>([]); const [logs,setLogs]=useState<Log[]>([]); const [diet,setDiet]=useState<string[]>([]); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();const patient=await supabase.from('patients').select('id').eq('user_id',user?.id||'').single();if(!patient.data){setLoading(false);return}const [rx,adherence,consultations]=await Promise.all([supabase.from('prescriptions').select('id,medicine_name,dosage,duration,instructions,meal_timing,frequency_note,morning,afternoon,evening,night,created_at').eq('patient_id',patient.data.id).order('created_at',{ascending:false}),supabase.from('medication_adherence_logs').select('prescription_id,time_of_day,status').eq('patient_id',patient.data.id).eq('scheduled_date',new Date().toISOString().slice(0,10)),supabase.from('consultations').select('diet_advice,created_at').eq('patient_id',patient.data.id).not('diet_advice','is',null).order('created_at',{ascending:false}).limit(1)]);setPrescriptions(rx.data||[]);setLogs(adherence.data||[]);setDiet(consultations.data?.[0]?.diet_advice?String(consultations.data[0].diet_advice).split('\n').filter(Boolean):[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 function statusFor(id:string,slot:string){return logs.find(log=>log.prescription_id===id&&log.time_of_day===slot)?.status}
 async function record(prescriptionId:string,timeOfDay:string,status:'taken'|'skipped'){const {data:{user}}=await supabase.auth.getUser();const patient=await supabase.from('patients').select('id').eq('user_id',user?.id||'').single();if(!patient.data)return;const {error}=await supabase.from('medication_adherence_logs').upsert({prescription_id:prescriptionId,patient_id:patient.data.id,scheduled_date:new Date().toISOString().slice(0,10),time_of_day:timeOfDay,status},{onConflict:'prescription_id,scheduled_date,time_of_day'});setNotice(error?.message||`Marked ${status}.`);if(!error)load()}
 async function enableReminders(){if(!('Notification' in window)){setNotice('Browser notifications are not available on this device. Use the routine below to track medicines.');return}const permission=await Notification.requestPermission();if(permission==='granted'){setNotice('Browser reminder permission is enabled. Keep this page open to receive today’s in-app reminder prompts.')}else setNotice('Notification permission was not granted. The routine remains available in the app.')}
 if(loading)return <section className="clinical-card mt-5 p-5 text-sm text-slate-500">Loading clinician-issued treatment plan…</section>;
 return <><section className="clinical-card mt-5 p-5"><p className="clinical-eyebrow">Clinician-issued prescription</p><div className="flex items-start justify-between gap-3"><div><h2 className="mt-1 text-xl font-extrabold">Medicine routine</h2><p className="mt-1 text-sm text-slate-600">Times are routine prompts. Follow the timing and instructions written by your clinician.</p></div><button type="button" className="btn-secondary shrink-0 text-xs" onClick={enableReminders}>Enable reminders</button></div>{notice&&<p className="mt-3 rounded-xl bg-cyan-50 p-3 text-sm text-cyan-900">{notice}</p>}{prescriptions.length===0?<p className="mt-4 text-sm text-slate-500">No clinician-issued prescriptions are available yet.</p>:<div className="mt-5 space-y-4">{slots.map(([label,time,key])=>{const scheduled=prescriptions.filter(item=>Boolean(item[key]));return <div key={label} className="rounded-xl border border-slate-200 p-3"><p className="font-bold text-calm">{label} <span className="font-normal text-slate-500">{time}</span></p>{scheduled.length===0?<p className="mt-1 text-sm text-slate-400">No scheduled medicine.</p>:scheduled.map(item=>{const status=statusFor(item.id,label);return <div key={item.id} className="mt-3 rounded-lg bg-slate-50 p-3"><p className="font-bold">{item.medicine_name}</p><p className="mt-1 text-sm text-slate-600">{[item.dosage,item.meal_timing,item.duration,item.instructions].filter(Boolean).join(' · ')}</p><div className="mt-2 flex gap-2"><button type="button" onClick={()=>record(item.id,label,'taken')} className={`rounded-lg px-3 py-1 text-xs font-bold ${status==='taken'?'bg-emerald-600 text-white':'bg-emerald-100 text-emerald-800'}`}>Taken</button><button type="button" onClick={()=>record(item.id,label,'skipped')} className={`rounded-lg px-3 py-1 text-xs font-bold ${status==='skipped'?'bg-amber-600 text-white':'bg-amber-100 text-amber-800'}`}>Skipped</button></div></div>})}</div>})}</div>}</section>{diet.length>0&&<section className="clinical-card mt-5 p-5"><p className="clinical-eyebrow">Doctor-approved guidance</p><h2 className="mt-1 text-xl font-extrabold">Diet plan</h2><p className="mt-2 text-sm text-slate-600">This plan was entered by your doctor. It is not automatically generated by the app.</p><ul className="mt-4 space-y-2 text-sm text-slate-700">{diet.map((line,index)=><li key={index} className="rounded-lg bg-slate-50 p-3">{line}</li>)}</ul></section>}</>;
}
