'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase';

export function VoiceRecordHelper(){
 const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState(''); const [listening,setListening]=useState(false);
 async function respond(value=question){const text=value.trim();if(!text)return;const {data:{user}}=await supabase.auth.getUser();const patient=await supabase.from('patients').select('id').eq('user_id',user?.id||'').single();if(!patient.data)return;const [reports,prescriptions,visits]=await Promise.all([supabase.from('reports').select('id',{count:'exact',head:true}).eq('patient_id',patient.data.id),supabase.from('prescriptions').select('id',{count:'exact',head:true}).eq('patient_id',patient.data.id),supabase.from('appointments').select('id',{count:'exact',head:true}).eq('patient_id',patient.data.id)]);const lower=text.toLowerCase();if(/report|document|रिपोर्ट/.test(lower))setAnswer(`Your record currently has ${reports.count||0} medical report(s). Open My documents to review the original report and its clinician-provided details.`);else if(/medicine|prescription|दवा|दवाई/.test(lower))setAnswer(`Your record has ${prescriptions.count||0} prescription item(s). Open My medicines or Records to review the clinician’s instructions.`);else if(/appointment|visit|मुलाकात/.test(lower))setAnswer(`Your record has ${visits.count||0} appointment(s). Open Appointments to see their status and check-in code.`);else setAnswer('I can help you find stored appointments, reports, prescriptions, and medicine history. Please ask about one of these records.');}
 function speak(){const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){setAnswer('Speech recognition is not available in this browser. You can type your record question instead.');return}const recognition=new Recognition();recognition.lang=localStorage.getItem('selectedSpeechLanguage')||'en-IN';recognition.interimResults=false;recognition.onstart=()=>setListening(true);recognition.onend=()=>setListening(false);recognition.onerror=()=>{setListening(false);setAnswer('I could not hear that. Try again or type your question.')};recognition.onresult=(event:any)=>{const heard=event.results[0][0].transcript;setQuestion(heard);respond(heard)};recognition.start();}
 return <section className="clinical-card mt-5 p-5"><p className="clinical-eyebrow">Your health records</p><h2 className="mt-1 text-xl font-extrabold">Speak to AarogyaVaani</h2><p className="mt-2 text-sm text-slate-600">Ask about information already stored in your records. This helper does not diagnose or give medical advice.</p><button type="button" onClick={speak} className="btn-primary mt-4 w-full">{listening?'Listening…':'🎙 Speak to AarogyaVaani'}</button><div className="mt-3 flex gap-2"><input className="input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Explain my latest medical report"/><button type="button" onClick={()=>respond()} className="btn-secondary whitespace-nowrap">Ask</button></div>{answer&&<div className="mt-3 rounded-xl bg-cyan-50 p-3 text-sm leading-6 text-cyan-950"><b>Record explanation</b><p>{answer}</p><p className="mt-2 text-xs">This is an automated record explanation, not a medical diagnosis. Consult your doctor for clinical decisions.</p></div>}</section>;
}
