// @ts-nocheck
'use client';

import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { PortalShell, Status } from '@/components/portal-shell';
import { PatientMedicineHistory } from '@/components/patient-medicine-history';
import { supabase } from '@/lib/supabase';

const labels:Record<string,string>={dashboard:'Your health at a glance',appointments:'Appointments',queue:'My queue',summary:'Health summary',medicines:'My medicines',prescriptions:'Prescriptions',reports:'Medical reports',documents:'Medical documents',symptoms:'Symptom history',family:'Family health records'};
function title(section:string){return labels[section]||'Patient portal'}
export default function PatientSection(){const {section}=useParams<{section:string}>();const router=useRouter();const [items,setItems]=useState<any[]>([]);const [name,setName]=useState('');const [loading,setLoading]=useState(true);const [notice,setNotice]=useState('');const [file,setFile]=useState<File|null>(null);const [uploading,setUploading]=useState(false);const isUpload=['documents','reports','prescriptions'].includes(section);
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/patient/login');return}const patient=await supabase.from('patients').select('id,full_name').eq('user_id',user.id).single();if(!patient.data){setNotice('Your patient profile is not ready. Confirm your email, then sign in again.');setLoading(false);return}setName(patient.data.full_name||'there');if(section==='medicines'){setLoading(false);return}let result:any;if(['appointments','queue','dashboard'].includes(section))result=await supabase.from('appointments').select('id,status,token_number,appointment_date,appointment_time,reason,doctors(full_name,department)').eq('patient_id',patient.data.id).order('appointment_date',{ascending:false});else if(section==='reports')result=await supabase.from('reports').select('*').eq('patient_id',patient.data.id).order('created_at',{ascending:false});else if(['documents','prescriptions'].includes(section))result=await supabase.from('medical_documents').select('*').eq('patient_id',patient.data.id).order('created_at',{ascending:false});else if(section==='symptoms')result=await supabase.from('symptom_entries').select('*').eq('patient_id',patient.data.id).order('recorded_at',{ascending:false});else if(section==='family')result=await supabase.from('family_members').select('*').eq('patient_id',patient.data.id).order('created_at',{ascending:false});setItems(result?.data||[]);setLoading(false)}
 useEffect(()=>{load()},[section]);
 async function upload(){if(!file)return;setUploading(true);setNotice('Saving document securely…');const {data:{user}}=await supabase.auth.getUser();const patient=await supabase.from('patients').select('id').eq('user_id',user?.id||'').single();if(!patient.data){setNotice('Your patient profile is not ready. Confirm your email, then sign in again.');setUploading(false);return}const path=`patients/${patient.data.id}/${section}/${crypto.randomUUID()}-${file.name}`;const up=await supabase.storage.from('medical-files').upload(path,file,{contentType:file.type});if(up.error){setNotice(`Upload failed: ${up.error.message}. Check that the medical-files bucket and storage policies were created by the initial migration.`);setUploading(false);return}const summary=`Patient-uploaded ${file.type.startsWith('image/')?'image':'document'}: ${file.name}. Original file retained for clinician review; automated OCR analysis is not configured in this deployment.`;const payload=section==='reports'?{patient_id:patient.data.id,report_type:'Patient uploaded report',title:file.name,report_date:new Date().toISOString().slice(0,10),storage_path:path,description:summary}:{patient_id:patient.data.id,document_type:section==='prescriptions'?'Patient-uploaded prescription':'Patient-uploaded document',title:file.name,document_date:new Date().toISOString().slice(0,10),storage_path:path,description:summary};const table=section==='reports'?'reports':'medical_documents';const saved=await supabase.from(table).insert(payload);setNotice(saved.error?`File uploaded but record could not be saved: ${saved.error.message}`:'Document saved in your private records. The doctor can review the original file and its record summary.');setFile(null);setUploading(false);load()}
 return <PortalShell role="patient" title={title(section)}>{section==='dashboard'&&<section className="rounded-2xl bg-gradient-to-r from-ink to-slate-700 p-6 text-white"><p className="text-teal-200">Welcome back</p><h2 className="mt-1 text-3xl font-black">{name}</h2><p className="mt-3 text-slate-200">Your care information, organized and protected.</p></section>}{section==='medicines'&&<><section className="rounded-2xl bg-gradient-to-r from-cyan-800 to-sky-700 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest">Care information</p><h2 className="mt-2 text-3xl font-extrabold">Medication history</h2><p className="mt-2 text-sm">Keep an accurate record of medicines you currently use for your care team.</p></section><PatientMedicineHistory/></>}{isUpload&&<section className="card mb-5 p-5"><p className="clinical-eyebrow">Private patient record</p><h2 className="mt-1 text-xl font-black">Upload {section==='reports'?'medical report':'document or prescription'}</h2><p className="mt-2 text-sm leading-6 text-slate-600">PDF, JPG, PNG, or WEBP up to 15 MB. The original is stored privately for clinician review.</p><input className="input mt-4" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/>{file&&<p className="mt-3 rounded-lg bg-cyan-50 p-3 text-sm">Selected: <b>{file.name}</b></p>}<button type="button" onClick={upload} disabled={!file||uploading} className="btn-primary mt-4 w-full">{uploading?'Saving securely…':'Save to patient records'}</button><p className="mt-3 text-xs text-slate-500">OCR/AI extraction requires a separately configured OCR provider. This app never invents a medical summary from an unread file.</p></section>}{notice&&<p className="mb-5 rounded-xl bg-teal-50 p-4 text-sm text-teal-800">{notice}</p>}<section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-black">{title(section)}</h2></div>{loading?<p className="p-6 text-slate-500">Loading private records…</p>:items.length===0&&section!=='dashboard'?<p className="p-6 text-slate-500">No records yet.</p>:<div className="divide-y">{items.map((item:any)=><article key={item.id} className="p-5"><p className="font-bold">{item.title||item.name||item.symptom_text||item.reason||'Care record'}</p><p className="mt-1 text-sm text-slate-500">{item.document_date||item.report_date||item.recorded_at||item.appointment_date||item.relationship||'Patient submitted'}</p>{item.description&&<p className="mt-2 text-sm leading-5 text-slate-600">{item.description}</p>}{item.status&&<Status tone={item.status==='completed'?'green':'amber'}>{item.status.replace('_',' ')}</Status>}</article>)}</div>}</section></PortalShell>}
