'use client';

import { FormEvent, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { LANGUAGE_STORAGE_KEY, languages, selectedSpeechLanguage } from '@/lib/languages';
import { supabase } from '@/lib/supabase';

export default function Symptoms(){
 const [stage,setStage]=useState<'choose'|'answer'>('choose'); const [language,setLanguage]=useState('en-IN'); const [mode,setMode]=useState<'voice'|'typing'>('voice'); const [text,setText]=useState(''); const [notice,setNotice]=useState(''); const [listening,setListening]=useState(false);
 useEffect(()=>setLanguage(localStorage.getItem(LANGUAGE_STORAGE_KEY)||'en-IN'),[]); function start(){localStorage.setItem(LANGUAGE_STORAGE_KEY,language);window.dispatchEvent(new Event('aarogyavaani-language'));setStage('answer')}
 async function save(event:FormEvent){event.preventDefault();const {data:{user}}=await supabase.auth.getUser();const {data:patient}=await supabase.from('patients').select('id').eq('user_id',user?.id??'').single();const {error}=await supabase.from('symptom_entries').insert({patient_id:patient?.id,symptom_text:text,input_method:mode==='voice'?'voice':'typed',language:selectedSpeechLanguage()});setNotice(error?.message||'Saved as patient-submitted information for your care team.');if(!error)setText('')}
 function speak(){const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){setNotice('Voice typing is not supported in this browser. Please type your symptoms.');return}const recognition=new Recognition();recognition.lang=selectedSpeechLanguage();recognition.onresult=(event:any)=>{setText(event.results[0][0].transcript);setListening(false)};recognition.onerror=()=>{setListening(false);setNotice('We could not understand the recording. Please type your symptoms.')};recognition.onend=()=>setListening(false);setListening(true);recognition.start()}
 if(stage==='choose')return <PortalShell role="patient" title="Health interview"><section className="mx-auto max-w-md rounded-[26px] border border-slate-200 bg-white p-5 shadow-soft"><p className="clinical-eyebrow">Patient-led clinical intake</p><h2 className="mt-1 text-2xl font-extrabold leading-tight">Tell your doctor what is going on.</h2><p className="mt-2 text-sm leading-6 text-slate-600">Share the main problem, when it started, what makes it better or worse, and any warning signs. AarogyaVaani organizes your information for review; it does not diagnose you.</p><p className="label mt-6">Language</p><div className="grid grid-cols-2 gap-3">{languages.map(item=><button key={item.code} type="button" onClick={()=>setLanguage(item.code)} className={`rounded-2xl border p-4 text-left ${language===item.code?'border-calm bg-cyan-50 ring-1 ring-calm':'border-slate-200 bg-white'}`}><b>{item.label}</b><span className="mt-1 block text-xs text-slate-500">India</span></button>)}</div><p className="label mt-6">How would you like to answer?</p><div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>setMode('voice')} className={`rounded-2xl border p-4 text-left ${mode==='voice'?'border-calm bg-cyan-50 ring-1 ring-calm':'border-slate-200'}`}><b>Voice + touch</b><span className="mt-1 block text-xs text-slate-500">Recommended</span></button><button type="button" onClick={()=>setMode('typing')} className={`rounded-2xl border p-4 text-left ${mode==='typing'?'border-calm bg-cyan-50 ring-1 ring-calm':'border-slate-200'}`}><b>Touch + typing</b><span className="mt-1 block text-xs text-slate-500">Quiet mode</span></button></div><button onClick={start} className="btn-primary mt-5 w-full rounded-2xl py-3.5">Start health interview</button></section></PortalShell>;
 return <PortalShell role="patient" title="Health interview"><section className="mx-auto max-w-md clinical-card overflow-hidden"><div className="bg-calm p-5 text-white"><button type="button" onClick={()=>setStage('choose')} className="text-sm font-semibold text-cyan-100">← Change language or answer mode</button><h2 className="mt-3 text-2xl font-extrabold">Tell us how you feel</h2><p className="mt-2 text-sm text-cyan-50">Describe the problem, when it began, severity, associated symptoms, and what you have tried.</p></div><form onSubmit={save} className="p-5"><label className="label">What are you experiencing?</label><textarea className="input min-h-40" value={text} onChange={event=>setText(event.target.value)} placeholder="Example: Fever began two days ago, with cough. It is worse at night. I have taken…" required/>{mode==='voice'&&<button type="button" className="btn-secondary mt-3 w-full" onClick={speak}>{listening?'Listening…':'🎤 Speak your answer'}</button>}<button className="btn-primary mt-3 w-full">Review & save</button>{notice&&<p className="mt-4 rounded-xl bg-cyan-50 p-3 text-sm text-cyan-900">{notice}</p>}<p className="mt-4 text-xs leading-5 text-slate-500">This does not provide a diagnosis. Seek emergency care for urgent symptoms.</p></form></section></PortalShell>;
}
