'use client';

import { useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { LANGUAGE_STORAGE_KEY, languages, selectedSpeechLanguage } from '@/lib/languages';
import { supabase } from '@/lib/supabase';

type Track = { name:string; questions:string[] };
function trackFor(problem:string):Track {
 const text=problem.toLowerCase();
 if(/chest|breath|breathing|heart|palpitation/.test(text)) return {name:'chest or breathing concern',questions:['When did it begin? Does it happen at rest, with activity, or after a specific trigger?','Do you have chest pressure, severe shortness of breath, sweating, nausea, fainting, or pain spreading to the arm, jaw, back, or shoulder?','How severe is it now from 0 to 10? Do you have heart/lung conditions, and what medicines or treatment have you already tried?']};
 if(/fever|cough|cold|throat|flu/.test(text)) return {name:'fever or respiratory concern',questions:['When did the fever, cough, or throat problem begin? What is the highest measured temperature?','Is there breathing difficulty, chest pain, confusion, dehydration, rash, or cough with blood?','Have you taken any medicine or test already, and do you have asthma, lung disease, allergies, or recent sick contacts?']};
 if(/stomach|abdomen|abdominal|vomit|nausea|diarr|loose motion|constipat/.test(text)) return {name:'stomach or bowel concern',questions:['Where exactly is the discomfort? When did it begin, and is it constant or does it come and go?','Do you have repeated vomiting, blood in vomit or stool, black stool, high fever, severe pain, or inability to keep fluids down?','What have you eaten or taken for this, and do you have prior stomach illness, surgery, pregnancy concerns, or medicine allergies?']};
 if(/head|migraine|dizz|vertigo|vision|weakness/.test(text)) return {name:'headache or neurological concern',questions:['When did the headache or dizziness start? Was it sudden, and is this different from previous episodes?','Do you have weakness, numbness, speech trouble, confusion, fainting, seizure, fever with stiff neck, or vision loss?','How severe is it from 0 to 10? What medication have you tried, and do you have migraine, blood-pressure, or other long-term conditions?']};
 if(/skin|rash|itch|allerg|swelling|hives/.test(text)) return {name:'skin or allergy concern',questions:['When did the rash, itching, or swelling begin? Where is it, and is it spreading?','Do you have fever, painful skin, blisters, face/lip swelling, wheezing, or trouble breathing?','Were there new medicines, foods, products, insect bites, or contacts before it began? What treatment have you tried?']};
 if(/urine|urinary|burn|kidney|pee/.test(text)) return {name:'urinary concern',questions:['When did the urinary symptoms begin? Do you have burning, urgency, lower abdominal pain, or back/flank pain?','Do you have fever, vomiting, blood in urine, pregnancy concerns, or inability to pass urine?','Have you had this before, taken antibiotics or other medicines, or had kidney/diabetes conditions?']};
 if(/joint|back|neck|muscle|injur|pain/.test(text)) return {name:'pain or injury concern',questions:['Where is the pain or injury, when did it start, and was there a fall, strain, or accident?','Is there swelling, deformity, numbness, weakness, inability to move or bear weight, fever, or loss of bladder/bowel control?','Rate the pain from 0 to 10. What medicines or home treatment have you tried, and what makes it better or worse?']};
 return {name:'general health concern',questions:['When did this problem start, and is it improving, worsening, or staying the same?','What symptoms are most troubling? Are there any urgent warning signs such as severe pain, breathing difficulty, fainting, confusion, heavy bleeding, or very high fever?','How is it affecting daily life? What medicines or treatments have you tried, and what allergies or long-term conditions should your doctor know?']};
}
function patientReportedSummary(answers:string[], track:Track|null){
 const text=answers.join(' ').toLowerCase();
 const redFlags=[['severe chest pain','Severe chest pain reported'],['shortness of breath','Breathing difficulty reported'],['cannot breathe','Breathing difficulty reported'],['faint','Fainting/unconsciousness reported'],['unconscious','Unconsciousness reported'],['weakness on one side','Stroke-like weakness reported'],['heavy bleeding','Heavy bleeding reported'],['face swelling','Possible severe allergic reaction reported']].filter(([term])=>text.includes(term)).map(([,label])=>label);
 return {chiefComplaint:answers[0]||'Not recorded',track:track?.name||'General health concern',responses:answers.slice(1),redFlags};
}

export default function Symptoms(){
 const [stage,setStage]=useState<'choose'|'interview'|'review'>('choose'); const [language,setLanguage]=useState('en-IN'); const [mode,setMode]=useState<'voice'|'typing'>('typing'); const [answers,setAnswers]=useState<string[]>([]); const [answer,setAnswer]=useState(''); const [notice,setNotice]=useState(''); const [listening,setListening]=useState(false);
 const track=useMemo(()=>answers[0]?trackFor(answers[0]):null,[answers]);
 useEffect(()=>setLanguage(localStorage.getItem(LANGUAGE_STORAGE_KEY)||'en-IN'),[]);
 function start(){localStorage.setItem(LANGUAGE_STORAGE_KEY,language);window.dispatchEvent(new Event('aarogyavaani-language'));setStage('interview')}
 function speak(){const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){setNotice('Voice typing is not supported in this browser. Please type your answer.');return}const recognition=new Recognition();recognition.lang=selectedSpeechLanguage();recognition.onresult=(event:any)=>{setAnswer(event.results[0][0].transcript);setListening(false)};recognition.onerror=()=>{setListening(false);setNotice('We could not understand the recording. Please type your answer.')};recognition.onend=()=>setListening(false);setListening(true);recognition.start()}
 function continueInterview(){if(!answer.trim()){setNotice('Please add an answer before continuing.');return}const next=[...answers,answer.trim()];setAnswers(next);setAnswer('');setNotice('');if(next.length>=4)setStage('review')}
 async function save(){const questions=['What is the main health problem or symptom you want help with?',...(track?.questions||[])];const combined=answers.map((item,index)=>`${questions[index]||'Additional information'}\n${item}`).join('\n\n');const {data:{user}}=await supabase.auth.getUser();const patient=await supabase.from('patients').select('id').eq('user_id',user?.id||'').single();const {error}=await supabase.from('symptom_entries').insert({patient_id:patient.data?.id,symptom_text:combined,input_method:mode==='voice'?'voice':'typed',language:selectedSpeechLanguage()});setNotice(error?.message||'Your structured history was saved for your care team.');if(!error){setAnswers([]);setStage('choose')}}
 if(stage==='choose')return <PortalShell role="patient" title="Health interview"><section className="clinical-card p-5"><p className="clinical-eyebrow">Patient-led clinical intake</p><h2 className="mt-1 text-2xl font-extrabold">Tell your doctor what is going on.</h2><p className="mt-2 text-sm leading-6 text-slate-600">Your first answer chooses focused follow-up questions for your concern. This organizes your history for clinical review; it does not diagnose you.</p><p className="label mt-6">Language</p><div className="grid grid-cols-2 gap-3">{languages.map(item=><button key={item.code} type="button" onClick={()=>setLanguage(item.code)} className={`rounded-xl border p-3 text-left ${language===item.code?'border-calm bg-cyan-50':'border-slate-200'}`}><b>{item.label}</b></button>)}</div><p className="label mt-6">Answer method</p><div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>setMode('voice')} className={`rounded-xl border p-3 text-left ${mode==='voice'?'border-calm bg-cyan-50':'border-slate-200'}`}>Voice + touch</button><button type="button" onClick={()=>setMode('typing')} className={`rounded-xl border p-3 text-left ${mode==='typing'?'border-calm bg-cyan-50':'border-slate-200'}`}>Touch + typing</button></div><button onClick={start} className="btn-primary mt-5 w-full">Start health interview</button>{notice&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}</section></PortalShell>;
 if(stage==='review'){const summary=patientReportedSummary(answers,track);return <PortalShell role="patient" title="Review health history"><section className="clinical-card p-5"><h2 className="text-xl font-extrabold">Review before sharing</h2><p className="mt-2 text-sm text-slate-600">Your doctor will see this patient-reported history. It is not a medical diagnosis.</p>{summary.redFlags.length>0&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><b>Urgent attention flag</b><p className="mt-1">{summary.redFlags.join(' · ')}. If symptoms are severe or worsening, seek urgent in-person care now.</p></div>}<div className="mt-4 rounded-xl bg-cyan-50 p-4 text-sm text-slate-700"><p className="clinical-eyebrow">Structured patient-reported summary</p><p className="mt-2"><b>Chief complaint:</b> {summary.chiefComplaint}</p><p className="mt-1"><b>Concern track:</b> {summary.track}</p><p className="mt-1"><b>Red flags:</b> {summary.redFlags.length?summary.redFlags.join(', '):'None reported in these answers'}</p><p className="mt-2 text-xs">This is a structured organization of your answers, not an AI diagnosis. Your doctor makes clinical decisions.</p></div><div className="mt-4 space-y-3">{answers.map((item,index)=><div key={index} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{index===0?'Main concern':track?.questions[index-1]}</b><p className="mt-1">{item}</p></div>)}</div><button onClick={save} className="btn-primary mt-5 w-full">Save for my care team</button><button onClick={()=>setStage('interview')} className="mt-3 w-full text-sm font-bold text-calm">Back and edit</button></section></PortalShell>;}
 const prompt=answers.length===0?'What is the main health problem or symptom you want help with?':track?.questions[answers.length-1]||'Is there anything else your doctor should know?';
 return <PortalShell role="patient" title="Health interview"><section className="clinical-card p-5"><p className="clinical-eyebrow">Question {answers.length+1} of 4{track&&answers.length>0?` · ${track.name}`:''}</p><h2 className="mt-2 text-xl font-extrabold">{prompt}</h2><textarea className="input mt-5 min-h-36" value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="Answer in your own words"/>{mode==='voice'&&<button type="button" onClick={speak} className="btn-secondary mt-3 w-full">{listening?'Listening…':'🎤 Speak your answer'}</button>}<button onClick={continueInterview} className="btn-primary mt-3 w-full">{answers.length===3?'Review history':'Continue'}</button>{notice&&<p className="mt-3 text-sm text-red-700">{notice}</p>}</section></PortalShell>;
}
